FROM public.ecr.aws/lambda/python:3.9

COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install -r requirements.txt --no-cache-dir

COPY handler.py ${LAMBDA_TASK_ROOT}/
COPY preprocessing.py ${LAMBDA_TASK_ROOT}/
COPY model.pkl ${LAMBDA_TASK_ROOT}/

CMD ["handler.lambda_handler"]
